# Copyright (c) OpenMMLab. All rights reserved.
from mmengine.registry import MODELS

CONV_LAYERS = MODELS
NORM_LAYERS = MODELS
ACTIVATION_LAYERS = MODELS
PADDING_LAYERS = MODELS
UPSAMPLE_LAYERS = MODELS
PLUGIN_LAYERS = MODELS

DROPOUT_LAYERS = MODELS
POSITIONAL_ENCODING = MODELS
ATTENTION = MODELS
FEEDFORWARD_NETWORK = MODELS
TRANSFORMER_LAYER = MODELS
TRANSFORMER_LAYER_SEQUENCE = MODELS
