void KernelFocalLossSigmoidForward(cnrtDim3_t k_dim,
                                   cnrtFunctionType_t k_type,
                                   cnrtQueue_t queue,
                                   cnrtDataType_t d_type,
                                   const void *input,
                                   const void *target,
                                   const void *weight,
                                   const int32_t N,
                                   const int32_t C,
                                   const float alpha,
                                   const float gamma,
                                   void *output);
