name: Build and publish mmcv (cp314-cp314-linux_x86_64)

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: [self-hosted, linux, X64, spot-runner, aws]
        steps:
            - name: Checkout to branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install pip utils
              shell: bash
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir twine

            - name: Compile mmcv
              shell: bash
              run: |
                  docker compose -f docker/builder.yml up -d --build --remove-orphans
                  docker compose -f docker/builder.yml cp builder:/io/dist/ dist/
                  docker compose -f docker/builder.yml down --remove-orphans

            - name: Upload wheel
              if: success()
              shell: bash
              env:
                  AZPYPI_PWD: ${{ secrets.AZPYPI_PASSWORD }}
              run: |
                  twine upload --repository-url https://pip.azmed.co:8870 \
                      -u "dev-team@azmed.co" -p "${AZPYPI_PWD}" dist/*
